<a href="https://colab.research.google.com/github/DmitriyValetov/nlp_course_project/blob/master/metrics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

# <pad>  - 0
# <unk>  - 1 
# <sos>  - 2 
# <eos>  - 3
# word A - 4
# word B - 5
eos = 3
# batch targets (batch size, batch length)
bts = np.array([
[2, 1, 4, 3, 0],  # target 1
[2, 1, 4, 5, 3],  # target 2
[2, 4, 3, 0, 0]   # target 3
])
# batch predictions (batch size, batch length)
bps = np.array([
[2, 1, 5, 1, 0],  # prediction 1
[2, 1, 5, 4, 3],  # prediction 2
[2, 4, 3, 0, 0]   # prediction 3
])

In [7]:
# set (unique) metrics (without order)
for sp, st in zip(bts, bps):
  # target to set
  st_eos_i = np.where(st==eos)[0][0] if eos in st else len(st)
  st_eos = st[:st_eos_i]
  t_set = set(st_eos) - {0, 1, 2, 3}
  # prediction to set
  sp_eos_i = np.where(sp==eos)[0][0] if eos in sp else len(sp)
  sp_eos = sp[:sp_eos_i]
  p_set = set(sp_eos) - {0, 1, 2, 3}
  # metrics
  i_set = t_set.intersection(p_set)
  pre = len(i_set)/len(p_set) if len(p_set) != 0 else 0
  rec = len(i_set)/len(t_set) if len(t_set) != 0 else 0
  f1 = 2*pre*rec/(pre + rec) if pre + rec != 0 else 0
  rl = len(sp_eos)/len(st_eos) if len(st_eos) != 0 else 0
  print(f'st: {st}, sp: {sp}')
  print(f'eos in st?: {eos in st}, sp_eos_i: {st_eos_i}')
  print(f'eos in sp?: {eos in sp}, sp_eos_i: {sp_eos_i}')
  print(f'st_eos: {st_eos}, sp_eos: {sp_eos}')
  print(f't_set: {t_set}, p_set: {p_set}')
  print(f'precision: {pre}, recall: {rec}, f1: {f1}. rl: {rl}\n')

st: [2 1 5 1 0], sp: [2 1 4 3 0]
eos in st?: False, sp_eos_i: 5
eos in sp?: True, sp_eos_i: 3
st_eos: [2 1 5 1 0], sp_eos: [2 1 4]
t_set: {5}, p_set: {4}
precision: 0.0, recall: 0.0, f1: 0. rl: 0.6

st: [2 1 5 4 3], sp: [2 1 4 5 3]
eos in st?: True, sp_eos_i: 4
eos in sp?: True, sp_eos_i: 4
st_eos: [2 1 5 4], sp_eos: [2 1 4 5]
t_set: {4, 5}, p_set: {4, 5}
precision: 1.0, recall: 1.0, f1: 1.0. rl: 1.0

st: [2 4 3 0 0], sp: [2 4 3 0 0]
eos in st?: True, sp_eos_i: 2
eos in sp?: True, sp_eos_i: 2
st_eos: [2 4], sp_eos: [2 4]
t_set: {4}, p_set: {4}
precision: 1.0, recall: 1.0, f1: 1.0. rl: 1.0



In [0]:
# accuracy (ordered)
pad_mask = bts != 0  # mask <pad> at target
m_bts = bts[pad_mask]  # mask targets
m_bps = bps[pad_mask]  # mask predictions like targets
comp = m_bts == m_bps  # compare
acc = np.sum(comp) / len(m_bts)
print(f'targets:\n{bts}')
print(f'predictions:\n{bps}')
print(f'pad_mask:\n{pad_mask}')
print(f'masked targets:\n{m_bts}')
print(f'masked predictions:\n{m_bps}')
print(f'comparison\n{comp}')
print(f'accuracy: {acc}')

targets:
[[2 1 4 3 0]
 [2 1 4 5 3]
 [2 4 3 0 0]]
predictions:
[[2 1 5 1 0]
 [2 1 5 4 3]
 [2 4 3 0 0]]
pad_mask:
[[ True  True  True  True False]
 [ True  True  True  True  True]
 [ True  True  True False False]]
masked targets:
[2 1 4 3 2 1 4 5 3 2 4 3]
masked predictions:
[2 1 5 1 2 1 5 4 3 2 4 3]
comparison
[ True  True False False  True  True False False  True  True  True  True]
accuracy: 0.6666666666666666
